// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: Desk_Screen

#include "../ui.h"

void ui_HomePage_screen_init(void)
{
    ui_HomePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgLogo = lv_img_create(ui_HomePage);
    lv_img_set_src(ui_imgLogo, &ui_img_zhang_png);
    lv_obj_set_width(ui_imgLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgLogo, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_imgLogo, ui_event_imgLogo, LV_EVENT_ALL, NULL);

}
