// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: Desk_Screen

#include "../ui.h"

void ui_LovePage_screen_init(void)
{
    ui_LovePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LovePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgLogo1 = lv_img_create(ui_LovePage);
    lv_img_set_src(ui_imgLogo1, &ui_img_love_png);
    lv_obj_set_width(ui_imgLogo1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgLogo1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgLogo1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgLogo1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgLogo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_imgLogo1, ui_event_imgLogo1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LovePage, ui_event_LovePage, LV_EVENT_ALL, NULL);

}
