// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: Desk_Screen

#include "../ui.h"

void ui_MenuPage_screen_init(void)
{
    ui_MenuPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MenuPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MenuPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnTime = lv_btn_create(ui_MenuPage);
    lv_obj_set_width(ui_btnTime, 90);
    lv_obj_set_height(ui_btnTime, 90);
    lv_obj_set_x(ui_btnTime, 0);
    lv_obj_set_y(ui_btnTime, 20);
    lv_obj_add_flag(ui_btnTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnTime, &ui_img_time_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWeather = lv_btn_create(ui_MenuPage);
    lv_obj_set_width(ui_btnWeather, 90);
    lv_obj_set_height(ui_btnWeather, 90);
    lv_obj_set_x(ui_btnWeather, 0);
    lv_obj_set_y(ui_btnWeather, 20);
    lv_obj_set_align(ui_btnWeather, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_btnWeather, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnWeather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnWeather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnWeather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnWeather, &ui_img_weather_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnWeather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnWeather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnHome = lv_btn_create(ui_MenuPage);
    lv_obj_set_width(ui_btnHome, 50);
    lv_obj_set_height(ui_btnHome, 50);
    lv_obj_set_x(ui_btnHome, 0);
    lv_obj_set_y(ui_btnHome, 50);
    lv_obj_set_align(ui_btnHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_btnHome, &ui_img_home_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnHome, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnHome, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnTime, ui_event_btnTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnWeather, ui_event_btnWeather, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnHome, ui_event_btnHome, LV_EVENT_ALL, NULL);

}
