// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: Desk_Screen

#include "../ui.h"

void ui_TimePage_screen_init(void)
{
    ui_TimePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TimePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TimePage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimePage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimePage_btnBack = lv_btn_create(ui_TimePage);
    lv_obj_set_width(ui_TimePage_btnBack, 40);
    lv_obj_set_height(ui_TimePage_btnBack, 40);
    lv_obj_set_x(ui_TimePage_btnBack, 9);
    lv_obj_set_y(ui_TimePage_btnBack, 9);
    lv_obj_add_flag(ui_TimePage_btnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TimePage_btnBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TimePage_btnBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TimePage_btnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimePage_btnBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_TimePage_btnBack, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TimePage_btnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TimePage_btnBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_time = lv_label_create(ui_TimePage);
    lv_obj_set_width(ui_label_time, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_label_time, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_label_time, 0);
    lv_obj_set_y(ui_label_time, -25);
    lv_obj_set_align(ui_label_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_time, "23:05:14");
    lv_obj_set_style_text_font(ui_label_time, &ui_font_BG40s4bpp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_date = lv_label_create(ui_TimePage);
    lv_obj_set_width(ui_label_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_date, 0);
    lv_obj_set_y(ui_label_date, 25);
    lv_obj_set_align(ui_label_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_date, "2024/03/15");
    lv_obj_set_style_text_font(ui_label_date, &ui_font_BG24s4bpp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_day = lv_label_create(ui_TimePage);
    lv_obj_set_width(ui_label_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_day, 0);
    lv_obj_set_y(ui_label_day, 70);
    lv_obj_set_align(ui_label_day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_day, "周一");
    lv_obj_set_style_text_font(ui_label_day, &ui_font_BG24s4bpp, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TimePage_btnBack, ui_event_TimePage_btnBack, LV_EVENT_ALL, NULL);

}
