// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: Desk_Screen

#include "../ui.h"

void ui_WeatherPage_screen_init(void)
{
    ui_WeatherPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WeatherPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WeatherPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeatherPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherPage_btnBack = lv_btn_create(ui_WeatherPage);
    lv_obj_set_width(ui_WeatherPage_btnBack, 40);
    lv_obj_set_height(ui_WeatherPage_btnBack, 40);
    lv_obj_set_x(ui_WeatherPage_btnBack, 9);
    lv_obj_set_y(ui_WeatherPage_btnBack, 9);
    lv_obj_add_flag(ui_WeatherPage_btnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WeatherPage_btnBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherPage_btnBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WeatherPage_btnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeatherPage_btnBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_WeatherPage_btnBack, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WeatherPage_btnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WeatherPage_btnBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_weather = lv_label_create(ui_WeatherPage);
    lv_obj_set_width(ui_label_weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_weather, 20);
    lv_obj_set_y(ui_label_weather, -30);
    lv_obj_set_align(ui_label_weather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_weather, "阴");
    lv_obj_set_style_text_font(ui_label_weather, &ui_font_LX40s4bpp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_location = lv_label_create(ui_WeatherPage);
    lv_obj_set_width(ui_label_location, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_location, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_location, 0);
    lv_obj_set_y(ui_label_location, 65);
    lv_obj_set_align(ui_label_location, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_location, "青岛");
    lv_obj_set_style_text_font(ui_label_location, &ui_font_BG30s4bpp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_temp = lv_label_create(ui_WeatherPage);
    lv_obj_set_width(ui_label_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_temp, 0);
    lv_obj_set_y(ui_label_temp, 20);
    lv_obj_set_align(ui_label_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_temp, "10℃");
    lv_obj_set_style_text_font(ui_label_temp, &ui_font_BG40s4bpp, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_weather_pic = lv_img_create(ui_WeatherPage);
    lv_img_set_src(ui_label_weather_pic, &ui_img_cloudy_png);
    lv_obj_set_width(ui_label_weather_pic, 32);
    lv_obj_set_height(ui_label_weather_pic, 32);
    lv_obj_set_x(ui_label_weather_pic, -40);
    lv_obj_set_y(ui_label_weather_pic, -30);
    lv_obj_set_align(ui_label_weather_pic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_label_weather_pic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_label_weather_pic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_WeatherPage_btnBack, ui_event_WeatherPage_btnBack, LV_EVENT_ALL, NULL);

}
