// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: Desk_Screen

#include "ui.h"
#include "ui_helpers.h"
#include "Application/System_Device.h"
///////////////////// VARIABLES ////////////////////


// SCREEN: ui_HomePage
void ui_HomePage_screen_init(void);
lv_obj_t * ui_HomePage;
void ui_event_imgLogo(lv_event_t * e);
lv_obj_t * ui_imgLogo;


// SCREEN: ui_LovePage
void ui_LovePage_screen_init(void);
void ui_event_LovePage(lv_event_t * e);
lv_obj_t * ui_LovePage;
void ui_event_imgLogo1(lv_event_t * e);
lv_obj_t * ui_imgLogo1;


// SCREEN: ui_MenuPage
void ui_MenuPage_screen_init(void);
lv_obj_t * ui_MenuPage;
void ui_event_btnTime(lv_event_t * e);
lv_obj_t * ui_btnTime;
void ui_event_btnWeather(lv_event_t * e);
lv_obj_t * ui_btnWeather;
void ui_event_btnHome(lv_event_t * e);
lv_obj_t * ui_btnHome;


// SCREEN: ui_TimePage
void ui_TimePage_screen_init(void);
lv_obj_t * ui_TimePage;
void ui_event_TimePage_btnBack(lv_event_t * e);
lv_obj_t * ui_TimePage_btnBack;
lv_obj_t * ui_label_time;
lv_obj_t * ui_label_date;
lv_obj_t * ui_label_day;


// SCREEN: ui_WeatherPage
void ui_WeatherPage_screen_init(void);
lv_obj_t * ui_WeatherPage;
void ui_event_WeatherPage_btnBack(lv_event_t * e);
lv_obj_t * ui_WeatherPage_btnBack;
lv_obj_t * ui_label_weather;
lv_obj_t * ui_label_location;
lv_obj_t * ui_label_temp;
lv_obj_t * ui_label_weather_pic;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_imgLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LovePage, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_LovePage_screen_init);
    }
    xTaskNotifyGive(Screen_Handle);
}
void ui_event_LovePage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomePage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HomePage_screen_init);
    }
    xTaskNotifyGive(Screen_Handle);
}
void ui_event_imgLogo1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuPage, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_MenuPage_screen_init);
    }
    xTaskNotifyGive(Screen_Handle);
}
void ui_event_btnTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_TimePage, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_TimePage_screen_init);
    }
    xTaskNotifyGive(Screen_Handle);
}
void ui_event_btnWeather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WeatherPage, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_WeatherPage_screen_init);
    }
    xTaskNotifyGive(Screen_Handle);
}
void ui_event_btnHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HomePage, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_HomePage_screen_init);
    }
    xTaskNotifyGive(Screen_Handle);
}
void ui_event_TimePage_btnBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuPage, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_MenuPage_screen_init);
    }
    xTaskNotifyGive(Screen_Handle);
}
void ui_event_WeatherPage_btnBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuPage, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_MenuPage_screen_init);
    }
    xTaskNotifyGive(Screen_Handle);
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HomePage_screen_init();
    ui_LovePage_screen_init();
    ui_MenuPage_screen_init();
    ui_TimePage_screen_init();
    ui_WeatherPage_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_HomePage);
}
