// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.2.0
// Project name: Desk_Screen

#ifndef _DESK_SCREEN_UI_H
#define _DESK_SCREEN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_HomePage
void ui_HomePage_screen_init(void);
extern lv_obj_t * ui_HomePage;
void ui_event_imgLogo(lv_event_t * e);
extern lv_obj_t * ui_imgLogo;
// SCREEN: ui_LovePage
void ui_LovePage_screen_init(void);
void ui_event_LovePage(lv_event_t * e);
extern lv_obj_t * ui_LovePage;
void ui_event_imgLogo1(lv_event_t * e);
extern lv_obj_t * ui_imgLogo1;
// SCREEN: ui_MenuPage
void ui_MenuPage_screen_init(void);
extern lv_obj_t * ui_MenuPage;
void ui_event_btnTime(lv_event_t * e);
extern lv_obj_t * ui_btnTime;
void ui_event_btnWeather(lv_event_t * e);
extern lv_obj_t * ui_btnWeather;
void ui_event_btnHome(lv_event_t * e);
extern lv_obj_t * ui_btnHome;
// SCREEN: ui_TimePage
void ui_TimePage_screen_init(void);
extern lv_obj_t * ui_TimePage;
void ui_event_TimePage_btnBack(lv_event_t * e);
extern lv_obj_t * ui_TimePage_btnBack;
extern lv_obj_t * ui_label_time;
extern lv_obj_t * ui_label_date;
extern lv_obj_t * ui_label_day;
// SCREEN: ui_WeatherPage
void ui_WeatherPage_screen_init(void);
extern lv_obj_t * ui_WeatherPage;
void ui_event_WeatherPage_btnBack(lv_event_t * e);
extern lv_obj_t * ui_WeatherPage_btnBack;
extern lv_obj_t * ui_label_weather;
extern lv_obj_t * ui_label_location;
extern lv_obj_t * ui_label_temp;
extern lv_obj_t * ui_label_weather_pic;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_zhang_png);    // assets\zhang.png
LV_IMG_DECLARE(ui_img_love_png);    // assets\love.png
LV_IMG_DECLARE(ui_img_time_png);    // assets\time.png
LV_IMG_DECLARE(ui_img_weather_png);    // assets\weather.png
LV_IMG_DECLARE(ui_img_home_png);    // assets\home.png
LV_IMG_DECLARE(ui_img_back_png);    // assets\back.png
LV_IMG_DECLARE(ui_img_cloudy_png);    // assets\cloudy.png
LV_IMG_DECLARE(ui_img_cloud_png);    // assets\cloud.png
LV_IMG_DECLARE(ui_img_qr_png);    // assets\QR.png
LV_IMG_DECLARE(ui_img_rain_png);    // assets\rain.png
LV_IMG_DECLARE(ui_img_snowy_png);    // assets\snowy.png
LV_IMG_DECLARE(ui_img_sunny_png);    // assets\sunny.png

LV_FONT_DECLARE(ui_font_BG24s4bpp);
LV_FONT_DECLARE(ui_font_BG30s4bpp);
LV_FONT_DECLARE(ui_font_BG40s4bpp);
LV_FONT_DECLARE(ui_font_LX34s4bpp);
LV_FONT_DECLARE(ui_font_LX40s4bpp);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
